### PR TITLE
PMM-10910 datfrozenxid metric

### PR DESCRIPTION
**Pull request by tshcherban**
https://jira.percona.com/browse/PMM-10910

### CODE REVIEW

**Comment by BupycHuk** [comment]
is this metric return id? And what's the cardinality of values for this metric?

**Comment by tshcherban** [comment]
@BupycHuk 
yep, that returns id of last non-'frozen' transaction. On my test setup (9.6, 11, 14 postgres) lots of duplicates

**Comment by rnovikovP** [comment]
@BupycHuk , I think we should close this one (see https://perconadev.atlassian.net/browse/PMM-10910?focusedCommentId=410471)

**Comment by BupycHuk** [comment]
@rnovikovP closed

**Pull request closed without merging**
